version: 2.1

jobs:
  code-quality:
    docker:
      - image: cimg/python:3.10.1
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_USER: multimedia
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: lint
          command: pylint my_media/ media_organizer/
      - run:
          name: run tests with coverage
          command: coverage run --source=my_media,media_organizer manage.py test && coverage xml -o coverage.xml

      # Almacenar resultados de las pruebas
      - store_test_results:
          path: test_results

      # Mostrar el informe de cobertura
      - run:
          name: show coverage report
          command: coverage report -m

      # Almacenar el informe de cobertura como artefacto
      - store_artifacts:
          path: coverage.xml

  build-and-push-to-dockerhub:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 24.0.7
          docker_layer_caching: true
      - run: |
          echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run: docker build -t jeffnacato/circle_ci_python:$CIRCLE_BRANCH .
      - run: docker push jeffnacato/circle_ci_python:$CIRCLE_BRANCH

workflows:
  build-and-test-workflow:
    jobs:
      - code-quality
      - build-and-push-to-dockerhub:
          requires:
            - code-quality

